version: 2
jobs:
  build:
    working_directory: ~/zellige
    docker:
      - image: circleci/ruby:2.4.4
    environment:
      ZIP_FILE: hastile_linux_${CIRCLE_BUILD_NUM}.zip
    steps:
      - checkout
      - restore-cache:
          keys:
            - stack{{checksum "stack-ci.yaml"}}
      - restore-cache:
          keys:
            - stack{{checksum "zellige.cabal"}}{{checksum "stack-ci.yaml"}}
      - run:
          name: Install deps
          command: |
            sudo apt-get install -y libgmp-dev
      - run:
          name: install
          command: |
            rm -rf ~/zellige/.stack-work/downloaded
            wget https://github.com/commercialhaskell/stack/releases/download/v1.7.1/stack-1.7.1-linux-x86_64.tar.gz -O /tmp/stack.tar.gz
            mkdir /tmp/stack/
            tar -xvzf /tmp/stack.tar.gz -C /tmp/stack/
            sudo mv /tmp/stack/stack-1.7.1-linux-x86_64/stack /usr/local/bin/stack
      - run:
          name: pre
          no_output_timeout: 60m
          command: |
            stack setup --stack-yaml stack-ci.yaml --no-terminal -j2
            stack build --stack-yaml stack-ci.yaml --no-system-ghc --only-configure --no-terminal -j2 --fast
      - run:
          name: compile
          no_output_timeout: 60m
          command: |
            stack build  --stack-yaml stack-ci.yaml --no-terminal -j2 --fast
      - run:
          name: test
          no_output_timeout: 60m
          command: |
            stack test  --stack-yaml stack-ci.yaml --no-terminal -j2 --fast
      - save-cache:
          key: stack{{checksum "stack-ci.yaml" }}
          paths:
            - "~/.stack"
      - save-cache:
          key: stack{{checksum "zellige.cabal"}}{{checksum "stack-ci.yaml" }}
          paths:
            - "~/zellige/.stack-work"
